import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SessionWrapper from "@/components/SessionWrapper";
import Chathistory from "@/components/ChatHistory";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Codebuddy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        </body>
    </html>
    </SessionWrapper>
  );
}
